#pragma once
#include <iostream>
using namespace std;
enum Tokens{
    RWORD,
    IDENT,
    END_OF_LINE,
    END_OF_FILE,
    TYPE_INT,TYPE_CHAR,TYPE_DOUBLE,TYPE_FLOAT,TYPE_LONG,TYPE_STRING,TYPE_SHORT,TYPE_BOOL,TYPE_ARRAY,
    AMPER,TILDE,PIPE,HAT,SEMICOLON,COLON,DOLLAR,AQUOTE,BQUOTE,SHARP,NOTE,QUESTION,
    /*& ~ | ^ ; : " ' $ # @ ?*/
    AND,OR,NOT,IF_EQUAL,NOT_EQUAL,
    /*&& || ! == !=*/
    PLUS,MINUS,STAR,SLASH,PERCENT,EQUAL,GREATER,LESS,
    /*+ - * / % = > <*/
    GREATER_EQUAL,LESS_EQUAL,PLUS_EQUAL,MINUS_EQUAL,STAR_EQUAL,SLASH_EQUAL,PERCENT_EQUAL,
    PLUS_PLUS,MINUS_MINUS,STAR_STAR,SLASH_SLASH,
    COMMA,DOT,LP,RP,LB,RB,LC,RC,
    /* , . ( ) [ ] { }*/
    IF,ELSE,TRUE,FALSE,WHILE,FOR,FUNCTION,REQUIRE,RETURN,BREAK,CONTINUE,
    INT,CHAR,DOUBLE,FLOAT,LONG,STRING,SHORT,BOOL,CLASS
};
